export const Colors = {
  light: {
    text: '#000000',
    background: '#E6EEFA',
    tint: '#4F55E3',
    icon: '#000000',
    tabIconDefault: '#cccccc',
    tabIconSelected: '#4F55E3',
    border: '#000000',
    surface: '#FFFFFF',
    primary: '#4B5AE1',
    green: '#AAEB85',
    yellow: '#FFCE54',
    pink: '#FF91B4',
    blueLight: '#99C3FF',
    grey: '#F0F0F0',
  },
  dark: {
    // For now, mirroring light mode to keep brutalism style consistent,
    // though dark mode could invert background and text.
    text: '#FFFFFF',
    background: '#1A1A1A',
    tint: '#4F55E3',
    icon: '#FFFFFF',
    tabIconDefault: '#888888',
    tabIconSelected: '#4F55E3',
    border: '#FFFFFF',
    surface: '#2C2C2C',
    primary: '#4F55E3',
    green: '#A8F087',
    yellow: '#FFCE54',
    pink: '#FF9BBE',
    blueLight: '#99C3FF',
    grey: '#333333',
  },
};
